### PR TITLE
Escape open angle brackets so that they're not interpreted as start states

### LINKED ISSUE #13: nimbleparse example in book fails
I'm trying out the basic `nimbleparse` example shown in the book but am getting an error around the lexer file. It looks like I have nimbparse built (and I add `target/release` to `PATH`). 

```
$ git clone git@github.com:softdevteam/grammars.git
$ pushd grammars; git rev-parse HEAD
b51fb08f25bbfcc8d0ae637599ec446bc63efdd1
$ popd
$ cat bad.java
class SyntaxError {
    int x y;
}
$ nimbleparse grammars/java7/java.l grammars/java7/java.y bad.java
grammars/java7/java.l: [Error] Invalid start state at line 71 column 1
```

Looks like these are due to `<` leading characters in the regular expressions (same at a couple of other lines). If I add a `\` to each `<` character, then it seems to work ok. Is this expected? The lexer section mentions this, but the `nimbleparse` example doesn't so was wondering if there is an option I should use to avoid this issue.

### PR DESCRIPTION
**Pull request by ltratt**
Also, while I'm here, consistently use `\<` rather than `[<]` as the escape mechanism.

Fixes https://github.com/softdevteam/grammars/issues/13.

### CODE REVIEW

**Comment by ptersilie** [comment]
I don't see any code with `[<]`. Is there a commit missing?

**Comment by ltratt** [comment]
I've checked and I've checked and... I can't see one, nor can I see any `[<]`. I think I might have confused this with one of the other repos I was working on -- or maybe I'm just going mad... OK for me to force push a commit update?

**Comment by ptersilie** [comment]
Go ahead.

**Comment by ltratt** [comment]
Force pushed.

**Review by ptersilie — APPROVED** [review]
Looks good.

**Pull request merged**
